services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    depends_on:
      - nestjs_db

  # ğŸ˜ PostgreSQL Database
  nestjs_db:
    image: postgres:15.5
    container_name: nestjs_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_database
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

    #---------------enable when we want with host access
    # networks:
    #   - nest_network

volumes:
  pgdata:
#------------------------For host---------------------->

# ğŸŒ Shared network between services (and accessible to host)
# networks:
#   nest_network:
#     driver: bridge
